(define SetOD
  (lambda (thickness Outer_diameter)
    (define Cylinder
      (insert:cylcone thickness Outer_diameter))
    (property:apply-name Cylinder "OD")
  )
)
;ex.(SetOD 0.022 0.75)
(define SetID 
  (lambda (thickness base_radius top_radius)
    (define Cone
      (insert:cylcone thickness base_radius base_radius top_radius))
	(property:apply-name Cone "ID")
  )
)
;ex.(SetID 0.022 0.65 0.5)
(define Subtract
  (lambda ( )
    (bool:subtract 
      (entity:get-by-name "OD") 
      (entity:get-by-name "ID") 
    )
  )
)
(define RefreshView
  (lambda ( )
    (view:profiles "yx")
    (view:zoom-all)
	(window:refresh-model)
  )
)
(define Main 
  (lambda(thickness Outer_diameter base_radius top_radius)
    (SetOD thickness Outer_diameter)
    (SetID thickness base_radius top_radius)
    (Subtract)
    (property:apply-name (entity:get-by-name "OD" ) "soma")
    (property:apply-surface (entity:get-by-name "soma" ) (list "Perfect Absorber" "Default"))
	;(property:apply-surface (tools:face-in-body 0 (entity:get-by-name "soma" )) (list "Perfect Mirror" "Default"))
    (entity:rotate (entity:get-by-name "soma") 0 0 0 0 1 0 90.000000 )
	(property:apply-color (entity:get-by-name "soma") 0 255 0 #t 0.8 0.8 0.8)
    (RefreshView)
  )
)
;ex.(Main 0.022 0.75 0.65 0.5)